# Runs a script to output commit to Google Spreadsheet
name: Update Commits

on:
  push:
    branches:
      - main
  workflow_dispatch: # manually triggered

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@25a956c84d5dd820d28caab9f86b8d183aeeff3d

      - name: Setup Python
        run: |
          pip3 install google-api-python-client google-auth-httplib2 google-auth-oauthlib
          echo "${{secrets.API_CREDS}}" | base64 -d > credentials.json

      - name: Run Commit Update
        run: |
          python3 ./scripts/update_commits.py
        env:
          COMMIT: ${{ github.sha }}
          AUTHOR: ${{ github.event.head_commit.author.email }}
          COMMENT: ${{ github.event.head_commit.message }}
